# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-06 04:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(blank=True, max_length=20, null=True, verbose_name='工作职位')),
                ('job_categories', models.CharField(blank=True, max_length=20, null=True, verbose_name='职位性质')),
                ('wage1', models.IntegerField(blank=True, null=True, verbose_name='最低工资')),
                ('wage2', models.IntegerField(blank=True, null=True, verbose_name='最高工资')),
                ('location', models.CharField(blank=True, max_length=25, null=True, verbose_name='地址')),
                ('work_experience', models.CharField(blank=True, max_length=10, null=True, verbose_name='工作经验')),
                ('education', models.CharField(blank=True, max_length=10, null=True, verbose_name='学历')),
                ('recruits_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='招聘人数')),
                ('company_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='公司名字')),
                ('company_type', models.CharField(blank=True, max_length=10, null=True, verbose_name='公司类型')),
                ('company_size', models.CharField(blank=True, max_length=10, null=True, verbose_name='公司规模')),
                ('company_address', models.CharField(blank=True, max_length=16, null=True, verbose_name='公司详细地址')),
                ('welfare_pos', models.CharField(blank=True, max_length=100, null=True, verbose_name='各种福利')),
                ('job_description', models.TextField(blank=True, null=True, verbose_name='工作详情')),
            ],
        ),
    ]
